"""全部 ORM 模型的汇总导入点。

⚠️ 新增模型文件后必须在此登记，否则 create_all / Alembic autogenerate 会漏表。
"""

from app.models.card import (
    LINK_POTENTIAL,
    LINK_REAL,
    ORIGIN_MANUAL,
    ORIGIN_PARENT_ANSWER,
    ORIGIN_PARENT_NOTE,
    ORIGIN_SOURCE_TEXT,
    REL_CONTINUATION,
    RELATIONS,
    SRC_BRAIN,
    SRC_COURSE,
    SRC_DOC,
    STATE_ARCHIVED,
    STATE_DRAFT,
    STATE_VAULT,
    Card,
    CardLink,
    CardMessage,
)
from app.models.course import (
    COURSE_DRAFT,
    COURSE_FAILED,
    COURSE_OUTLINING,
    COURSE_READY,
    SECTION_FAILED,
    SECTION_GENERATING,
    SECTION_PENDING,
    SECTION_READY,
    Chapter,
    Course,
    Section,
)
from app.models.document import DocBlock, Document
from app.models.graph import Workspace, WorkspaceEdge, WorkspaceNode
from app.models.learning import (
    POMO_ABANDONED,
    POMO_COMPLETED,
    POMO_RUNNING,
    Badge,
    Pomodoro,
    Quiz,
    ReviewLog,
    ReviewState,
)
from app.models.system import AICall, BlockSearch, CardSearch, Feedback, LLMCache
from app.models.user import RefreshToken, User

__all__ = [
    "AICall",
    "Badge",
    "BlockSearch",
    "Feedback",
    "COURSE_DRAFT",
    "COURSE_FAILED",
    "COURSE_OUTLINING",
    "COURSE_READY",
    "Card",
    "CardLink",
    "CardMessage",
    "CardSearch",
    "Chapter",
    "Course",
    "DocBlock",
    "Document",
    "LINK_POTENTIAL",
    "LINK_REAL",
    "LLMCache",
    "ORIGIN_MANUAL",
    "ORIGIN_PARENT_ANSWER",
    "ORIGIN_PARENT_NOTE",
    "ORIGIN_SOURCE_TEXT",
    "POMO_ABANDONED",
    "POMO_COMPLETED",
    "POMO_RUNNING",
    "REL_CONTINUATION",
    "RELATIONS",
    "Pomodoro",
    "RefreshToken",
    "Quiz",
    "ReviewLog",
    "ReviewState",
    "SECTION_FAILED",
    "SECTION_GENERATING",
    "SECTION_PENDING",
    "SECTION_READY",
    "SRC_BRAIN",
    "SRC_COURSE",
    "SRC_DOC",
    "STATE_ARCHIVED",
    "STATE_DRAFT",
    "STATE_VAULT",
    "Section",
    "User",
    "Workspace",
    "WorkspaceEdge",
    "WorkspaceNode",
]
